name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-6667b94c2095f8000108ac87-7404d27a3d593c782cb35f6778d5bd5e20
      - name: Run API tests
        run: |
          # Lint your API using Postman CLI
          postman api lint 0af6b4be-1e78-4d25-869f-c52375b9533a
